version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./target:/app/target
    entrypoint: mvn spring-boot:run -f /app
